"""
visualize_pt.py
---------------
Generates a visual validation plot from a Phase 1 extracted ``.pt`` file.

The script loads a single ``.pt`` tensor payload generated by
``pipeline_runner.py`` and produces a 3-row matplotlib figure:

    Row 1:  Five evenly-spaced RGB face crops (224×224).
    Row 2:  Corresponding 1-channel SRM residual noise maps.
    Row 3:  Smoothed rPPG temporal signal (R, G, B averages over time).

Output images are saved to:  ``visual_test_logs/<video_name>_validation.png``

Usage (CLI):
    # From the project root (deepfake/):
    python visual_testing/visualize_pt.py  test_output/DFDC/video_name.pt

    # Visualize a specific DeeperForensics output:
    python visual_testing/visualize_pt.py  test_output/DeeperForensics/774_M013.pt

Usage (Python):
    from visual_testing.visualize_pt import visualize_pt_file
    visualize_pt_file("test_output/DFDC/video_name.pt")
"""

import torch
import numpy as np
import matplotlib.pyplot as plt
import argparse
from pathlib import Path


# ======================================================================
#  Main visualization function
# ======================================================================
def visualize_pt_file(pt_path: str):
    """
    Load a ``.pt`` tensor payload and render a 3-row validation figure.

    Parameters
    ----------
    pt_path : str
        Path to the ``.pt`` file (e.g., ``test_output/DFDC/video.pt``).
    """
    pt_path = Path(pt_path)

    if not pt_path.exists():
        print(f"  [ERROR]  File not found: {pt_path}")
        return

    # ------------------------------------------------------------------
    #  1. Load the tensor dict
    # ------------------------------------------------------------------
    print(f"\n{'=' * 60}")
    print(f"  VISUAL VALIDATION")
    print(f"{'=' * 60}")
    print(f"  Loading : {pt_path}")

    data = torch.load(str(pt_path), weights_only=False)

    # Extract the 3 visual tensors and convert to NumPy
    face_crops    = data.get("face_crops")
    residual_maps = data.get("residual_maps")
    rppg_signals  = data.get("rppg_signals")

    if face_crops is not None:
        face_crops = face_crops.cpu().numpy()
    if residual_maps is not None:
        residual_maps = residual_maps.cpu().numpy()
    if rppg_signals is not None:
        rppg_signals = rppg_signals.cpu().numpy()

    # Validate that all 3 required tensors are present
    if face_crops is None or residual_maps is None or rppg_signals is None:
        print("  [ERROR]  Missing required tensors (face_crops / residual_maps / rppg_signals).")
        return

    # ------------------------------------------------------------------
    #  2. Print a quick metadata summary
    # ------------------------------------------------------------------
    T = face_crops.shape[0]

    print(f"  Video   : {data.get('video_name', '?')}")
    print(f"  Dataset : {data.get('dataset', '?')}")
    print(f"  Label   : {data.get('label', '?')}")
    print(f"  Frames  : {T}")
    print(f"  Crops   : {face_crops.shape}")
    print(f"  Resid.  : {residual_maps.shape}")
    print(f"  rPPG    : {rppg_signals.shape}")
    print(f"{'=' * 60}\n")

    # ------------------------------------------------------------------
    #  3. Select 5 evenly-spaced frame indices to display
    # ------------------------------------------------------------------
    indices = np.linspace(0, T - 1, min(5, T), dtype=int)

    fig = plt.figure(figsize=(16, 10))
    dataset = data.get('dataset', '?')
    video_name = data.get('video_name', '?')
    label = data.get('label', '?')
    manip_type = data.get('manipulation_type', '')

    title_str = f"Visual Validation  |  {dataset}  |  {video_name}  |  {label}"
    if manip_type:
        title_str += f" ({manip_type})"

    fig.suptitle(title_str, fontsize=14, fontweight="bold")

    # ------------------------------------------------------------------
    #  Row 1: RGB face crops
    # ------------------------------------------------------------------
    for i, idx in enumerate(indices):
        ax = plt.subplot(3, 5, i + 1)
        crop = face_crops[idx]

        # Values > 1.0 indicate uint8 range (0–255); cast for imshow
        if crop.max() > 1.0:
            crop = crop.astype(np.uint8)

        ax.imshow(crop)
        ax.set_title(f"Face Crop\nFrame {idx}", fontsize=9)
        ax.axis("off")

    # ------------------------------------------------------------------
    #  Row 2: Grayscale SRM residual maps
    # ------------------------------------------------------------------
    for i, idx in enumerate(indices):
        ax = plt.subplot(3, 5, i + 6)

        # Squeeze (224, 224, 1) → (224, 224) for matplotlib
        res = residual_maps[idx].squeeze()

        ax.imshow(res, cmap="viridis")
        ax.set_title(f"SRM Residual\nFrame {idx}", fontsize=9)
        ax.axis("off")

    # ------------------------------------------------------------------
    #  Row 3: Smoothed rPPG temporal signal
    # ------------------------------------------------------------------
    ax = plt.subplot(3, 1, 3)
    time_axis = np.arange(T)

    ax.plot(time_axis, rppg_signals[:, 0], color="red",   label="Red",   alpha=0.8)
    ax.plot(time_axis, rppg_signals[:, 1], color="green", label="Green", alpha=0.8)
    ax.plot(time_axis, rppg_signals[:, 2], color="blue",  label="Blue",  alpha=0.8)

    ax.set_title("Smoothed rPPG Signal (Skin ROI RGB Intensities)", fontsize=11)
    ax.legend(loc="upper right", fontsize=8)
    ax.set_xlabel("Frame Index")
    ax.set_ylabel("Intensity")
    ax.grid(True, linestyle="--", alpha=0.4)

    plt.tight_layout()

    # ------------------------------------------------------------------
    #  4. Save the figure
    # ------------------------------------------------------------------
    out_dir = Path("visual_test_logs")
    out_dir.mkdir(parents=True, exist_ok=True)
    out_filename = out_dir / f"{pt_path.stem}_validation.png"

    plt.savefig(str(out_filename), dpi=150)
    plt.close(fig)

    print(f"  [OK]  Plot saved → {out_filename}\n")


# ======================================================================
#  CLI entry point
# ======================================================================
if __name__ == "__main__":
    parser = argparse.ArgumentParser(
        description="Generate a visual validation plot from a Phase 1 .pt file.",
        epilog="Example:  python visual_testing/visualize_pt.py  test_output/DFDC/video.pt",
    )
    parser.add_argument(
        "pt_file",
        type=str,
        help="Path to the .pt file (e.g., test_output/DFDC/video_name.pt)",
    )
    args = parser.parse_args()

    visualize_pt_file(args.pt_file)
